### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by tigrazone** [lukedan/ReSTIR-Vulkan#2]
Hello!
Can you create and publish release for windows?
I can't build and want to check executable

**Comment by lukedan** [comment]
Hello,

Unfortunately, my access to GitHub is currently fairly spotty, making it difficult to perform any kind of upload. Do you mind sharing what issues you’re facing building the project?


From: dmitry
Sent: Sunday, January 8, 2023 2:26 AM
To: lukedan/ReSTIR-Vulkan
Cc: Subscribed
Subject: [lukedan/ReSTIR-Vulkan] Release (Issue #2)

Hello!
Can you create and publish release for windows?
I can't build and want to check executable

**Comment by tigrazone** [comment]
I cant build by minGW. See cmake output
CMake Error at CMakeLists.txt:80 (find_package):
  Could not find a package configuration file provided by "imgui" with any of
  the following names:

    imguiConfig.cmake
    imgui-config.cmake

  Add the installation prefix of "imgui" to CMAKE_PREFIX_PATH or set
  "imgui_DIR" to a directory containing one of the above files.  If "imgui"
  provides a separate development package or SDK, be sure it has been
  installed.

On Visual Studio I have cmake error
CMake Error at CMakeLists.txt:97 (find_package):
  Could not find a package configuration file provided by "gflags" with any
  of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.
  
Please describe steps to build

**Comment by lukedan** [comment]
Have you tried installing the packages mentioned in the error messages?
